/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RequestImport } from './routes/request'

// Create Virtual Routes

const EmbedLazyImport = createFileRoute('/embed')()
const IndexLazyImport = createFileRoute('/')()
const EmbedIndexLazyImport = createFileRoute('/embed/')()
const EmbedSendLazyImport = createFileRoute('/embed/send')()
const EmbedFaucetLazyImport = createFileRoute('/embed/faucet')()
const EmbedPermissionsIndexLazyImport = createFileRoute('/embed/permissions/')()
const EmbedPermissionsAppURLLazyImport = createFileRoute(
  '/embed/permissions/$appURL',
)()

// Create/Update Routes

const EmbedLazyRoute = EmbedLazyImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/embed.lazy').then((d) => d.Route))

const RequestRoute = RequestImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/request.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const EmbedIndexLazyRoute = EmbedIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmbedLazyRoute,
} as any).lazy(() => import('./routes/embed/index.lazy').then((d) => d.Route))

const EmbedSendLazyRoute = EmbedSendLazyImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => EmbedLazyRoute,
} as any).lazy(() => import('./routes/embed/send.lazy').then((d) => d.Route))

const EmbedFaucetLazyRoute = EmbedFaucetLazyImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => EmbedLazyRoute,
} as any).lazy(() => import('./routes/embed/faucet.lazy').then((d) => d.Route))

const EmbedPermissionsIndexLazyRoute = EmbedPermissionsIndexLazyImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => EmbedLazyRoute,
} as any).lazy(() =>
  import('./routes/embed/permissions.index.lazy').then((d) => d.Route),
)

const EmbedPermissionsAppURLLazyRoute = EmbedPermissionsAppURLLazyImport.update(
  {
    id: '/permissions/$appURL',
    path: '/permissions/$appURL',
    getParentRoute: () => EmbedLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/embed/permissions.$appURL.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestImport
      parentRoute: typeof rootRoute
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedLazyImport
      parentRoute: typeof rootRoute
    }
    '/embed/faucet': {
      id: '/embed/faucet'
      path: '/faucet'
      fullPath: '/embed/faucet'
      preLoaderRoute: typeof EmbedFaucetLazyImport
      parentRoute: typeof EmbedLazyImport
    }
    '/embed/send': {
      id: '/embed/send'
      path: '/send'
      fullPath: '/embed/send'
      preLoaderRoute: typeof EmbedSendLazyImport
      parentRoute: typeof EmbedLazyImport
    }
    '/embed/': {
      id: '/embed/'
      path: '/'
      fullPath: '/embed/'
      preLoaderRoute: typeof EmbedIndexLazyImport
      parentRoute: typeof EmbedLazyImport
    }
    '/embed/permissions/$appURL': {
      id: '/embed/permissions/$appURL'
      path: '/permissions/$appURL'
      fullPath: '/embed/permissions/$appURL'
      preLoaderRoute: typeof EmbedPermissionsAppURLLazyImport
      parentRoute: typeof EmbedLazyImport
    }
    '/embed/permissions/': {
      id: '/embed/permissions/'
      path: '/permissions'
      fullPath: '/embed/permissions'
      preLoaderRoute: typeof EmbedPermissionsIndexLazyImport
      parentRoute: typeof EmbedLazyImport
    }
  }
}

// Create and export the route tree

interface EmbedLazyRouteChildren {
  EmbedFaucetLazyRoute: typeof EmbedFaucetLazyRoute
  EmbedSendLazyRoute: typeof EmbedSendLazyRoute
  EmbedIndexLazyRoute: typeof EmbedIndexLazyRoute
  EmbedPermissionsAppURLLazyRoute: typeof EmbedPermissionsAppURLLazyRoute
  EmbedPermissionsIndexLazyRoute: typeof EmbedPermissionsIndexLazyRoute
}

const EmbedLazyRouteChildren: EmbedLazyRouteChildren = {
  EmbedFaucetLazyRoute: EmbedFaucetLazyRoute,
  EmbedSendLazyRoute: EmbedSendLazyRoute,
  EmbedIndexLazyRoute: EmbedIndexLazyRoute,
  EmbedPermissionsAppURLLazyRoute: EmbedPermissionsAppURLLazyRoute,
  EmbedPermissionsIndexLazyRoute: EmbedPermissionsIndexLazyRoute,
}

const EmbedLazyRouteWithChildren = EmbedLazyRoute._addFileChildren(
  EmbedLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/request': typeof RequestRoute
  '/embed': typeof EmbedLazyRouteWithChildren
  '/embed/faucet': typeof EmbedFaucetLazyRoute
  '/embed/send': typeof EmbedSendLazyRoute
  '/embed/': typeof EmbedIndexLazyRoute
  '/embed/permissions/$appURL': typeof EmbedPermissionsAppURLLazyRoute
  '/embed/permissions': typeof EmbedPermissionsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/request': typeof RequestRoute
  '/embed/faucet': typeof EmbedFaucetLazyRoute
  '/embed/send': typeof EmbedSendLazyRoute
  '/embed': typeof EmbedIndexLazyRoute
  '/embed/permissions/$appURL': typeof EmbedPermissionsAppURLLazyRoute
  '/embed/permissions': typeof EmbedPermissionsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/request': typeof RequestRoute
  '/embed': typeof EmbedLazyRouteWithChildren
  '/embed/faucet': typeof EmbedFaucetLazyRoute
  '/embed/send': typeof EmbedSendLazyRoute
  '/embed/': typeof EmbedIndexLazyRoute
  '/embed/permissions/$appURL': typeof EmbedPermissionsAppURLLazyRoute
  '/embed/permissions/': typeof EmbedPermissionsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/request'
    | '/embed'
    | '/embed/faucet'
    | '/embed/send'
    | '/embed/'
    | '/embed/permissions/$appURL'
    | '/embed/permissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/request'
    | '/embed/faucet'
    | '/embed/send'
    | '/embed'
    | '/embed/permissions/$appURL'
    | '/embed/permissions'
  id:
    | '__root__'
    | '/'
    | '/request'
    | '/embed'
    | '/embed/faucet'
    | '/embed/send'
    | '/embed/'
    | '/embed/permissions/$appURL'
    | '/embed/permissions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RequestRoute: typeof RequestRoute
  EmbedLazyRoute: typeof EmbedLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RequestRoute: RequestRoute,
  EmbedLazyRoute: EmbedLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/request",
        "/embed"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/request": {
      "filePath": "request.tsx"
    },
    "/embed": {
      "filePath": "embed.lazy.tsx",
      "children": [
        "/embed/faucet",
        "/embed/send",
        "/embed/",
        "/embed/permissions/$appURL",
        "/embed/permissions/"
      ]
    },
    "/embed/faucet": {
      "filePath": "embed/faucet.lazy.tsx",
      "parent": "/embed"
    },
    "/embed/send": {
      "filePath": "embed/send.lazy.tsx",
      "parent": "/embed"
    },
    "/embed/": {
      "filePath": "embed/index.lazy.tsx",
      "parent": "/embed"
    },
    "/embed/permissions/$appURL": {
      "filePath": "embed/permissions.$appURL.lazy.tsx",
      "parent": "/embed"
    },
    "/embed/permissions/": {
      "filePath": "embed/permissions.index.lazy.tsx",
      "parent": "/embed"
    }
  }
}
ROUTE_MANIFEST_END */
