/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface HappyReceipt {
  gasCost: bigint;
  gasUsed: bigint;
  happyTxHash: `0x${string}`;
  id: number | null;
  revertData: `0x${string}`;
  status: string;
  transactionHash: `0x${string}`;
}

export interface HappyState {
  happyReceiptId: number | null;
  happyTransactionId: number;
  id: number | null;
  included: boolean;
  status: string;
}

export interface HappyTransaction {
  account: `0x${string}`;
  callData: `0x${string}`;
  dest: `0x${string}`;
  entryPoint: `0x${string}`;
  executeGasLimit: bigint;
  extraData: `0x${string}`;
  gasLimit: bigint;
  happyTxHash: `0x${string}`;
  id: number | null;
  maxFeePerGas: bigint;
  nonceTrack: bigint;
  nonceValue: bigint;
  paymaster: `0x${string}`;
  paymasterData: `0x${string}`;
  submitterFee: bigint;
  validateGasLimit: bigint;
  validatePaymentGasLimit: bigint;
  validatorData: `0x${string}`;
  value: bigint;
}

export interface DB {
  happy_receipts: HappyReceipt;
  happy_states: HappyState;
  happy_transactions: HappyTransaction;
}
