export const overrides = {
    columns: {
        "happy_receipts.gasCost": "bigint",
        "happy_receipts.gasUsed": "bigint",
        "happy_receipts.happyTxHash": "`0x${string}`",
        "happy_receipts.nonceTrack": "bigint",
        "happy_receipts.nonceValue": "bigint",
        "happy_receipts.revertData": "`0x${string}`",
        "happy_receipts.transactionHash": "`0x${string}`",
        "happy_simulations.executeGas": "bigint",
        "happy_simulations.gas": "bigint",
        "happy_simulations.revertData": "`0x${string}`",
        "happy_simulations.entryPoint": "`0x${string}`",
        "happy_states.included": "boolean",
        "happy_transactions.account": "`0x${string}`",
        "happy_transactions.callData": "`0x${string}`",
        "happy_transactions.dest": "`0x${string}`",
        "happy_transactions.entryPoint": "`0x${string}`",
        "happy_transactions.executeGasLimit": "bigint",
        "happy_transactions.extraData": "`0x${string}`",
        "happy_transactions.gasLimit": "bigint",
        "happy_transactions.happyTxHash": "`0x${string}`",
        "happy_transactions.maxFeePerGas": "bigint",
        "happy_transactions.nonceTrack": "bigint",
        "happy_transactions.nonceValue": "bigint",
        "happy_transactions.paymaster": "`0x${string}`",
        "happy_transactions.paymasterData": "`0x${string}`",
        "happy_transactions.submitterFee": "bigint",
        "happy_transactions.validatorData": "`0x${string}`",
        "happy_transactions.value": "bigint",
    },
}
