// This file is auto-generated by `make deploy` in `contracts/Makefile`
import type { MapTuple, ObjectFromTuples, UnionToTuple } from "@happy.tech/common"
import type { Address } from "viem"


const contractToAbi = ({
  "HappyEntryPoint": null,
  "ScrappyAccount": null,
  "ScrappyAccountFactory": null,
  "ScrappyPaymaster": null
}
) as const

const aliasToContract = ({
  "HappyEntryPoint": "HappyEntryPoint",
  "ScrappyAccount": "ScrappyAccount",
  "ScrappyAccountFactory": "ScrappyAccountFactory",
  "ScrappyPaymaster": "ScrappyPaymaster"
}) as const

export const deployment = ({
  "HappyEntryPoint": "0x8B875dd38a222737183a165519dcd52768d8b99f",
  "ScrappyAccount": "0x95d8b82a439Df73d29DC84DcB347083a66244650",
  "ScrappyAccountFactory": "0x264F1B27861402B1bC55199b23B7cB4B71022025",
  "ScrappyPaymaster": "0x7f26e5DE61003caB1d154CE63202cD7B387B76E7"
}) as const

export type ContractToAbi = typeof contractToAbi
export type AliasToContract = typeof aliasToContract
export type ContractName = keyof ContractToAbi
export type ContractAlias = keyof AliasToContract
export type Deployment = Record<ContractAlias, Address>

type AliasTuple = UnionToTuple<ContractAlias>
type AbiValuesTuple = MapTuple<MapTuple<AliasTuple, AliasToContract>, ContractToAbi>

export type StaticAbis = ObjectFromTuples<AliasTuple, AbiValuesTuple>

export const abis = {} as StaticAbis

for (const [alias, contractName] of Object.entries(aliasToContract)) {
    // biome-ignore lint/suspicious/noExplicitAny: safe generated code
    abis[alias as ContractAlias] = contractToAbi[contractName as ContractName] as any
}


