# Full reference
# https://book.getfoundry.sh/reference/config/

[profile.default]
# For Cancun hardfork + enables transient variables support.
solc_version = "0.8.28"

optimizer = true
optimizer_runs = 20000
via_ir = true

ignored_warnings_from = ["node_modules", "lib", "src/deploy", "src/scripts", "src/test"]

# Compiler profiles for contracts that require via_ir enabled
additional_compiler_profiles = [
  { name = "kernel", via_ir = true, optimizer = true, optimizer_runs = 200 },
]

# Restrict Kernel.sol and Boop Contracts to use the Kernel and Boop profiles, respectively
compilation_restrictions = [
  { paths = "lib/kernel/src/Kernel.sol", via_ir = true, optimizer = true, optimizer_runs = 200 },
]

# Forge targets Paris by default.
evm_version = "cancun"

# Flags needed for OpenZeppelin upgrade validation.
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# Needed to write from the deploy scripts.
fs_permissions = [
    { access = "read", path = "./deployments/anvil/aa/deployment.json" },
    { access = "read", path = "./deployments/happy-sepolia/aa/deployment.json" },
    { access = "read", path = "./out/deployment.json" },
    { access = "write", path = "./out/deployment.json" },
    { access = "write", path = "./out/abiMap.json" },
]

# Formatter Options
line_width = 120

# allow all paths — necessary for pnpm
allow_paths = ["/"]

[profile.ci]
# Gives super verbose output by default (-vvvv) when running tests on CI.
verbosity = 4
