# Full reference
# https://book.getfoundry.sh/reference/config/

[profile.default]
# This is the last version safe for chains that haven't adopted to the Shangai hardfork EVM changes.
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 20000
gas_reports = ["*"]
via_ir = false

# Add compiler profiles for AA contracts
additional_compiler_profiles = [
  { name = "kernel", via_ir = true },
  { name = "aa", via_ir = false }
]

compilation_restrictions = [
  { paths = "lib/kernel/src/Kernel.sol", via_ir = true },
  { paths = "lib/kernel/src/Kernel.sol", optimizer = true, optimizer_runs = 200  }
]

# Forge targets Paris by default.
evm_version = "cancun"

# Flags needed for OpenZeppelin upgrade validation.
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# Needed to write from the deploy scripts.
fs_permissions = [
    { access = "read", path = "./deployments/anvil/testing/deployment.json" },
    { access = "read", path = "./out/deployment.json" },
    { access = "write", path = "./out/deployment.json" },
    { access = "write", path = "./out/abiMap.json" },
]

# Formatter Options
line_width = 120

# allow all paths — necessary for pnpm
allow_paths = ["/"]

[profile.ci]
# Gives super verbose output by default (-vvvv) when running tests on CI.
verbosity = 4
