/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Boop {
  account: `0x${string}`;
  boopHash: `0x${string}`;
  callData: `0x${string}`;
  dest: `0x${string}`;
  entryPoint: `0x${string}`;
  executeGasLimit: number;
  extraData: `0x${string}`;
  gasLimit: number;
  maxFeePerGas: bigint;
  nonceTrack: bigint;
  nonceValue: bigint;
  payer: `0x${string}`;
  submitterFee: bigint;
  validateGasLimit: number;
  validatePaymentGasLimit: number;
  validatorData: `0x${string}`;
  value: bigint;
}

export interface EvmReceipt {
  blockHash: `0x${string}`;
  blockNumber: bigint;
  boopHash: `0x${string}`;
  effectiveGasPrice: bigint;
  from: `0x${string}`;
  gasUsed: bigint;
  status: string;
  to: `0x${string}`;
  transactionHash: `0x${string}`;
}

export interface Receipt {
  boopHash: `0x${string}`;
  gasCost: bigint;
  revertData: `0x${string}`;
  status: string;
  txHash: `0x${string}`;
}

export interface DB {
  boops: Boop;
  evm_receipts: EvmReceipt;
  receipts: Receipt;
}
