/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Boop {
  account: `0x${string}`;
  boopHash: `0x${string}`;
  callData: `0x${string}`;
  dest: `0x${string}`;
  entryPoint: `0x${string}`;
  executeGasLimit: number;
  extraData: `0x${string}`;
  gasLimit: number;
  id: number;
  maxFeePerGas: bigint;
  nonceTrack: bigint;
  nonceValue: bigint;
  payer: `0x${string}`;
  submitterFee: bigint;
  validateGasLimit: number;
  validatePaymentGasLimit: number;
  validatorData: `0x${string}`;
  value: bigint;
}

export interface Receipt {
  boopHash: `0x${string}`;
  gasCost: bigint;
  gasUsed: bigint;
  id: number;
  revertData: `0x${string}`;
  status: string;
  txHash: `0x${string}`;
}

export interface State {
  boopId: number;
  id: number;
  included: boolean;
  receiptId: number | null;
  status: string;
}

export interface DB {
  boops: Boop;
  receipts: Receipt;
  states: State;
}
