/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RequestImport } from './routes/request'

// Create Virtual Routes

const SendLazyImport = createFileRoute('/send')()
const EmbedLazyImport = createFileRoute('/embed')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SendLazyRoute = SendLazyImport.update({
  path: '/send',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/send.lazy').then((d) => d.Route))

const EmbedLazyRoute = EmbedLazyImport.update({
  path: '/embed',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/embed.lazy').then((d) => d.Route))

const RequestRoute = RequestImport.update({
  path: '/request',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/request.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestImport
      parentRoute: typeof rootRoute
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedLazyImport
      parentRoute: typeof rootRoute
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  RequestRoute,
  EmbedLazyRoute,
  SendLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/request",
        "/embed",
        "/send"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/request": {
      "filePath": "request.tsx"
    },
    "/embed": {
      "filePath": "embed.lazy.tsx"
    },
    "/send": {
      "filePath": "send.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
