/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RequestImport } from './routes/request'

// Create Virtual Routes

const ConnectLazyImport = createFileRoute('/connect')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ConnectLazyRoute = ConnectLazyImport.update({
    path: '/connect',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/connect.lazy').then((d) => d.Route))

const RequestRoute = RequestImport.update({
    path: '/request',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/request.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
    path: '/',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexLazyImport
            parentRoute: typeof rootRoute
        }
        '/request': {
            id: '/request'
            path: '/request'
            fullPath: '/request'
            preLoaderRoute: typeof RequestImport
            parentRoute: typeof rootRoute
        }
        '/connect': {
            id: '/connect'
            path: '/connect'
            fullPath: '/connect'
            preLoaderRoute: typeof ConnectLazyImport
            parentRoute: typeof rootRoute
        }
    }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
    IndexLazyRoute,
    RequestRoute,
    ConnectLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/request",
        "/connect"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/request": {
      "filePath": "request.tsx"
    },
    "/connect": {
      "filePath": "connect.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
