name: happy-bundler

services:
  bundler:
    image: ghcr.io/happychaindevs/happy-bundler:latest
    ports:
      - "49531:49531"
    networks:
      - bundler_network
    environment:
      - BUNDLER_EXECUTOR_WALLET
      - BUNDLER_UTILITY_WALLET
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 4s
      timeout: 1s
      retries: 3
    restart: always

networks:
  bundler_network:
    driver: bridge
