name: Deploy staging iframe

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build code
        run: |
          cat > apps/iframe/.env <<-EOF
          VITE_FIREBASE_API_KEY="AIzaSyAx6idMmETQKhyPJeCQ3l62fMLEn3ZLwRw"
          VITE_FIREBASE_AUTH_DOMAIN="happytech-staging.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID="happytech-staging"
          VITE_FIREBASE_STORAGE_BUCKET="happytech-staging.firebasestorage.app"
          VITE_FIREBASE_MESSAGE_SENDER_ID="658209801994"
          VITE_FIREBASE_APP_ID="1:658209801994:web:5308b68401ae9b03151cf3"
          VITE_WEB3AUTH_CLIENT_ID="BEicEwse7BdJ1UU5pYG4EpRvm-64fE8_Qd8BgvoRNNzTaojockVhkjDNE3KJXrBSfThJJr0w_U8Kn76PO4hrwOE"
          VITE_WEB3AUTH_NETWORK="sapphire_devnet"
          VITE_WEB3AUTH_VERIFIER="firebase-2"
          VITE_BUNDLER_RPC_URL="https://bundler-staging.happy.tech"
          VITE_TURNSTILE_SITEKEY=0x4AAAAAABRnNdBbR6oFMviC
          VITE_FAUCET_ENDPOINT=https://faucet.testnet.happy.tech/faucet
          VITE_SUBMITTER_URL=https://submitter-staging.happy.tech
          VITE_CHAIN_ID=216
          EOF
          make setup
          make iframe.build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "apps/iframe/dist"
          target: /home/deployer/staging-iframe
          strip_components: 3 # Remove the first 3 levels of directories from the source path to copy only the files inside dist
          rm: true

      - name: Deploy staging iframe to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod -R o+rX /home/deployer/staging-iframe
            mv /home/deployer/staging-iframe /tmp
            sudo -u staging_iframe bash -c '
              rm -rf /var/www/staging-iframe/*
              cp -r /tmp/staging-iframe/* /var/www/staging-iframe
            '
            rm -rf /tmp/staging-iframe