name: Deploy staging iframe

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build code
        run: |
          printf "${{ vars.STAGING_IFRAME_ENV }}" > apps/iframe/.env
          make setup
          make iframe.build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "apps/iframe/dist"
          target: /home/deployer/staging-iframe
          strip_components: 3 # Remove the first 3 levels of directories from the source path to copy only the files inside dist
          rm: true

      - name: Deploy staging iframe to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod -R o+rX /home/deployer/staging-iframe
            mv /home/deployer/staging-iframe /tmp
            sudo -u staging_iframe bash -c '
              rm -rf /var/www/staging-iframe/*
              cp -r /tmp/staging-iframe/* /var/www/staging-iframe
            '
            rm -rf /tmp/staging-iframe