name: Deploy iframe

on:
  workflow_dispatch:
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
      
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Build code
        run: |
          cd packages/iframe
          make build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "packages/iframe/dist"
          target: /home/deployer/iframe
          strip_components: 3
          rm: true

      - name: Deploy bundler to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod -R o+rX /home/deployer/iframe
            mv /home/deployer/iframe /tmp
            sudo -u iframe bash -c '
              rm -rf /var/www/iframe
              cp -r /tmp/iframe /var/www/iframe
            '
            rm -rf /tmp/iframe