name: Deploy iframe

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: '1.2.4'

      - name: Build code
        run: |
          cat > apps/iframe/.env <<-EOF
          VITE_TURNSTILE_SITEKEY=0x4AAAAAABRnNdBbR6oFMviC
          VITE_FAUCET_ENDPOINT=https://faucet.testnet.happy.tech/faucet
          VITE_SUBMITTER_URL=https://submitter.happy.tech
          VITE_CHAIN_ID=216
          VITE_DEPLOYMENT=PROD
          VITE_FIREBASE_API_KEY_PROD="AIzaSyC63JTgST12DhmWG5xz3bhgKkpXALdcfhQ"
          VITE_FIREBASE_AUTH_DOMAIN_PROD="happytech-1c86e.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID_PROD="happytech-1c86e"
          VITE_FIREBASE_STORAGE_BUCKET_PROD="happytech-1c86e.firebasestorage.app"
          VITE_FIREBASE_MESSAGE_SENDER_ID_PROD="903671289585"
          VITE_FIREBASE_APP_ID_PROD="1:903671289585:web:0c597b1836b0bfa8e17b50"
          VITE_WEB3AUTH_CLIENT_ID_PROD="BAhlcPh6j9gJ3y1OclMfpEzvksJ-Vgq6YYIVYvn0SOkudbCyG4IXxRpuQer0WkDpr3MHITkOJtKfoBysLvfCDqc"
          VITE_WEB3AUTH_NETWORK_PROD="sapphire_devnet"
          VITE_WEB3AUTH_VERIFIER_PROD="firebase-1"
          EOF
          make setup
          make iframe.build

      - name: Copy files to server
        uses: appleboy/scp-action@917f8b81dfc1ccd331fef9e2d61bdc6c8be94634 # v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "apps/iframe/dist"
          target: /home/deployer/iframe
          strip_components: 3 # Remove the first 3 levels of directories from the source path to copy only the files inside dist
          rm: true

      - name: Deploy iframe to server
        uses: appleboy/ssh-action@25ce8cbbcb08177468c7ff7ec5cbfa236f9341e1 # v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod -R o+rX /home/deployer/iframe
            mv /home/deployer/iframe /tmp
            sudo -u iframe bash -c '
              rm -rf /var/www/iframe/*
              cp -r /tmp/iframe/* /var/www/iframe
            '
            rm -rf /tmp/iframe
