name: Deploy Monitor Service

on:
  workflow_dispatch:

env:
  PM2_PROCESS_NAME: monitor-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      
      - name: Build code
        run: |
          make monitor-service.build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "apps/monitor-service/build/*"
          target: /home/deployer/monitor-service
          strip_components: 2
          rm: true
          debug: true

      - name: Deploy fund monitor to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod -R o+rX /home/deployer/monitor-service
            rm -rf /tmp/monitor-service
            mv /home/deployer/monitor-service /tmp
            sudo -u monitor_service bash -c '
              rm -rf /home/monitor_service/build
              cp -r /tmp/monitor-service/* /home/monitor_service/build

              cd /home/monitor_service
    
              rm -f .env

              cat > .env <<-EOF
            export PRIVATE_KEY=${{ secrets.MONITOR_SERVICE_PRIVATE_KEY }}
            export NODE_ENV=production
            export BLOCK_TIME=2
            export CHAIN_ID=216
            export RPC_URL=https://rpc.testnet.happy.tech/http
            export MONITOR_ADDRESSES=0x10EBe5E4E8b4B5413D8e1f91A21cE4143B6bd8F5,0x3cBD2130C2D4D6aDAA9c9054360C29e00d99f0BA,0xBAc858b1AD51527F3c4A22f146246c9913e97cFd,0x84dcb507875af1786bb6623a625d3f9aae9fda4f,0xAE45fD410bf09f27DA574D3EF547567A479F4594,0x71E30C67d58015293f452468E4754b18bAFFd807,0xE55b09F1b78B72515ff1d1a0E3C14AD5D707fdE8,0x634de6fbFfE60EE6D1257f6be3E8AF4CfefEf697,0xe8bD127b013600E5c6f864e5C07E918fa80BFF89
            export FUND_THRESHOLD=10000000000000000
            export FUNDS_TO_SEND=10000000000000000
            export TXM_DB_PATH=/home/monitor_service/txm.sqlite
            export RPCS_TO_MONITOR=https://rpc.testnet.happy.tech/http,http://148.113.212.211:8545
            export RPC_MONITOR_INTERVAL=1000
            export SLACK_WEBHOOK_URL=${{ secrets.MONITOR_SERVICE_SLACK_WEBHOOK_URL }}
            export LOG_COLORS=true
            export LOG_TIMESTAMPS=true
            export SUBMITTERS_TO_MONITOR=https://submitter-staging.happy.tech,https://submitter.happy.tech
            export SUBMITTER_MONITOR_INTERVAL_MS=600000
            EOF
              # cf. https://github.com/appleboy/drone-ssh/issues/175
              sed -i '/DRONE_SSH_PREV_COMMAND_EXIT_CODE/d' .env

              bun ./build/migrate.es.js
            '
            sudo /bin/systemctl restart monitor_service.service
