name: Deploy submitter

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ORGANIZATION: happychaindevs
  PORT: 49534
  LOG_LEVEL: info

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build code
        run: |
          make submitter.build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "apps/submitter/build/*,packages/submitter/build/cli"
          target: /home/deployer/happy-submitter
          strip_components: 2   
          rm: true

      - name: Deploy submitter to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod -R o+rX /home/deployer/happy-submitter
            mv /home/deployer/happy-submitter /tmp
            sudo -u submitter bash -c '
              rm -rf /home/submitter/build
              cp -r /tmp/happy-submitter/* /home/submitter/build
              
              ls -R /tmp/happy-submitter
              cp /tmp/happy-submitter/packages/submitter/build/cli /home/submitter/build/submitter-cli
              /home/submitter/build/submitter-cli migrate latest

              cat > /home/submitter/build/.env <<-EOF
            PRIVATE_KEY_LOCAL=${{ secrets.SUBMITTER_PRIVATE_KEY_LOCAL }}
            PRIVATE_KEY_ACCOUNT_DEPLOYER=${{ secrets.SUBMITTER_PRIVATE_KEY_ACCOUNT_DEPLOYER }}
            ${{vars.SUBMITTER_ENV}}
            EOF
            '
            rm -rf /tmp/happy-submitter
            sudo /bin/systemctl restart submitter.service