name: Deploy submitter

on:
  workflow_dispatch:
  pull_request:

env:
  REGISTRY: ghcr.io
  ORGANIZATION: happychaindevs
  PM2_PROCESS_NAME: happy-staging-bundler
  PORT: 49533
  RPC_URL: https://rpc.testnet.happy.tech/http

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build code
        run: |
          make submitter.build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "apps/submitter/build/*"
          target: /home/deployer/happy-submitter
          strip_components: 2   
          rm: true

      - name: Deploy submitter to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod -R o+rX /home/deployer/happy-submitter
            mv /home/deployer/happy-submitter /tmp
            sudo -u submitter bash -c '
              rm -rf /home/submitter/build
              cp -r /tmp/happy-submitter/* /home/submitter/build
            '
            rm -rf /tmp/happy-submitter
            sudo /bin/systemctl restart submitter.service
      
      - name: Send chainId request (healthcheck)
        run: |
          sleep 10 # wait for the server to start
          curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' ${{ env.STAGING_BUNDLER_URL }} --fail