name: Deploy Faucet

on:
  workflow_dispatch:

env:
  PM2_PROCESS_NAME: faucet
  FAUCET_DB_PATH: /home/faucet/faucet.sqlite
  TXM_DB_PATH: /home/faucet/txm.sqlite


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: '1.2.4'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
      
      - name: Build code
        run: |
          make faucet.build

      - name: Copy files to server
        uses: appleboy/scp-action@917f8b81dfc1ccd331fef9e2d61bdc6c8be94634 # v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "apps/faucet/build/*,node_modules/better-sqlite3,node_modules/bindings,node_modules/file-uri-to-path"
          target: /home/deployer/faucet
          strip_components: 1   
          rm: true

      - name: Deploy faucet to server
        uses: appleboy/ssh-action@25ce8cbbcb08177468c7ff7ec5cbfa236f9341e1 # v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          # We copy better-sqlite3, bindings, and file-uri-to-path separately because the bundled file does not include
          # better-sqlite3 and its dependencies
          script: |
            chmod -R o+rX /home/deployer/faucet
            mv /home/deployer/faucet /tmp
            sudo -u faucet bash -c '
              rm -rf /home/faucet/build
              rm -rf /home/faucet/node_modules
              cp -r /tmp/faucet/faucet/build /home/faucet/build

              mkdir -p /home/faucet/node_modules
              cp -r /tmp/faucet/better-sqlite3 /home/faucet/node_modules/better-sqlite3
              cp -r /tmp/faucet/bindings /home/faucet/node_modules/bindings
              cp -r /tmp/faucet/file-uri-to-path /home/faucet/node_modules/file-uri-to-path
          
              cd /home/faucet
    
              rm -f .env

              cat > .env <<-EOF
            export PRIVATE_KEY=${{ secrets.FAUCET_PRIVATE_KEY }}
            export TURNSTILE_SECRET=${{ secrets.FAUCET_TURNSTILE_SECRET }}
            export BLOCK_TIME=2
            export CHAIN_ID=216
            export RPC_URL=https://rpc.testnet.happy.tech/http
            export APP_PORT=49533
            export NODE_ENV=production
            export TOKEN_AMOUNT=10000000000000000
            export FAUCET_RATE_LIMIT_WINDOW_SECONDS=86400
            export TXM_DB_PATH=/home/faucet/txm.sqlite
            export FAUCET_DB_PATH=/home/faucet/faucet.sqlite
            EOF

              dos2unix .env

              npm rebuild
            
              pm2 delete ${{ env.PM2_PROCESS_NAME }}
        
              source .env && node ./build/migrate.es.js

              source .env && pm2 start ./build/index.es.js \
                    --name ${{ env.PM2_PROCESS_NAME }}
              pm2 save
            '
            rm -rf /tmp/faucet
