name: Submitter Check Cron Job

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'       # every 30 min
env:
    CHAIN_ID: 216
    SUBMITTER_URL: "https://submitter.happy.tech"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: '1.2.4'
      - name: Build submitter & boop sdk
        run: |
            make submitter.build
      - name: Execute boop
        run: |
          cd apps/submitter/bin
          bun executeDummyBoop.ts

