name: Staging Submitter Check Cron Job

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # every 30 min
env:
    CHAIN_ID: 216
    VITE_SUBMITTER_URL: "https://submitter.happy.tech"
    # These don't get used but need to be provided.
    EXECUTOR_KEYS: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    DATABASE_URL: "dummy.sqlite"
    SUBMITTER_URL: "https://submitter-staging.happy.tech"
    LOG_COLORS: false
    LOG_TIMESTAMPS: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: '1.2.4'
      - name: Build submitter & boop sdk
        run: |
            make submitter.build
      - name: Execute boop
        run: |
          cd apps/submitter/bin
          bun executeDummyBoop.ts
      # - name: Send failure to Slack
      #   if: failure() # Only on failure
      #   uses: slackapi/slack-github-action@v2.1.0
      #   with:
      #     method: chat.postMessage
      #     token: ${{ secrets.SLACK_WORKFLOW_BOT_TOKEN }}
      #     payload: |
      #       {
      #         "channel": "C08JMNRJNR1",
      #         "text": "❌ Workflow *${{ github.workflow }}* failed on *${{ github.ref_name }}*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Failing Workflow Logs>"
      #       }
