name: Submitter Check Cron Job

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'       # every 30 min
env:
    CHAIN_ID: 216
    SUBMITTER_URL: "https://submitter.happy.tech"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: '1.2.4'
      - name: Build submitter & boop sdk
        run: |
            make submitter.build
      - name: Execute boop
        run: |
          cd support/testing
          bun executeDummyBoop.ts
      - name: Send failure to Slack
        if: failure() # Only on failure
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "channel": "#alerts",
              "text": "❌ Workflow *${{ github.workflow }}* failed on *${{ github.ref_name }}*\n<$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/${{ github.run_id }}|View Logs>"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_WORKFLOW_BOT_TOKEN }}
