name: Test Contracts

on:
  pull_request:
    paths:
      - 'contracts/**'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: default
  PRIVATE_KEY_LOCAL: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" # Forge/Anvil test private key 0

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
            submodules: recursive
            
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.34'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
            
      - name: Test contracts
        run: |
            make setup
            cd contracts
            forge test -vvv
