name: Test Contracts

on:
  pull_request:
    paths:
      - 'contracts/**'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: default

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
            submodules: recursive
            
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.34'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
            
      - name: Compile contracts
        run: |
            make setup
            cd contracts
            forge test -vvv
