name: Test Submitter Package

on:
  pull_request:
    paths:
      - 'apps/submitter/**'
      - 'contracts/deployments/anvil/boop/**'
      - 'contracts/deployments/anvil/mocks/**'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  CHAIN_ID: 31337
  EXECUTOR_KEYS: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  PRIVATE_KEY_ACCOUNT_DEPLOYER: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  APP_PORT: 3001
  AUTOMINE_TESTS: true
  LOG_LEVEL: "TRACE"
  DATABASE_URL: "submitter-tests.sqlite"
  LOG_COLORS: false
  LOG_TIMESTAMPS: false

jobs:
  test-submitter:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
            submodules: recursive
      
      - name: Install Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: '1.2.4'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
            
      - name: Install dependencies
        run: make setup
    
      # This step uses the default Anvil test private key (account #0)
      # The key is publicly known and should NEVER be used in production environments
      - name: Create test deployer key
        run: |
           cast wallet import --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --unsafe-password "password" test-account-0
           cd contracts && echo "password" > .password.local
      
      - name: Test Submitter package
        run: |
            cd apps/submitter
            make test
