name: Test TXM Package

on:
  pull_request:
    paths:
      - 'packages/txm/**'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  VITE_IFRAME_URL: "https://iframe.happy.tech"
  VITE_SUBMITTER_URL: "-"
  VITE_FIREBASE_API_KEY: "-"
  VITE_FIREBASE_AUTH_DOMAIN: "-"
  VITE_FIREBASE_PROJECT_ID: "-"
  VITE_FIREBASE_STORAGE_BUCKET: "-"
  VITE_FIREBASE_MESSAGE_SENDER_ID: "-"
  VITE_FIREBASE_APP_ID: "-"
  VITE_WEB3AUTH_CLIENT_ID: "-"
  VITE_WEB3AUTH_NETWORK: "-"
  VITE_WEB3AUTH_VERIFIER: "-"
  FOUNDRY_PROFILE: default

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
            submodules: recursive
  
      - name: Install Node23 (for tests)
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 23
      
      - name: Install Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: '1.2.4'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
            
      - name: Compile contracts
        run: |
            make setup
            cd contracts
            forge build -vvvv
    
      # This step uses the default Anvil test private key (account #0)
      # The key is publicly known and should NEVER be used in production environments
      - name: Create test deployer key
        run: |
           cast wallet import --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80  --unsafe-password  "password" test-account-0
           cd contracts && echo "password" > .password.local
      
      - name: Build txm packages
        run: | 
            make txm.build
      
      - name: Test txm package
        run: |
            cd packages/txm
            make test
