name: Test Contracts

on:
  pull_request:
    paths:
      - 'contracts/**'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: default
  PRIVATE_KEY_LOCAL: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" # Forge/Anvil test private key 0

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
            submodules: recursive
            
      - name: Install Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: '1.1.34'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
            
      - name: Test contracts
        run: |
            make setup
            cd contracts
            make test
